### ISSUE TITLE
metaKEGG missing on pypi.org

### ISSUE THREAD

**Issue by motey** [dife-bioinformatics/metaKEGG#2]
Releaseday! Hey! :fireworks: 

 @mlazaratos  There is a hint in the README that [metaKEGG will be available on pypi.org](https://github.com/dife-bioinformatics/metaKEGG?tab=readme-ov-file#install-from-pypi)

But i can not find over there. That would make the build&deploy process for https://github.com/DZD-eV-Diabetes-Research/meta-kegg-web-wrapper much easier.

![image](https://github.com/user-attachments/assets/77ab3e36-19d0-4694-8eb2-4ca0592d833b)

**Comment by mlazaratos** [comment]
@motey Thanks a lot! :bowtie:

v1.0.0 is online!

https://pypi.org/project/metaKEGG/
